sql:
  host: ""
  database: ""
  port: ""
  user: ""
  pass: ""

#Enter Commands into the [] separated by a , (Comma)
#Basic Format for Minecraft Give Command

rankReward:
  Egg: []
  Chicken: []
  Wolf: []
  Lion: []
  Phoenix: []
  Griffin: []
  Manticore: []
  Dragon: []
